### PR TITLE
fix

### PR DESCRIPTION
**Pull request by Ccode-lang**

### CODE REVIEW

**Comment by Ccode-lang** [comment]
fix vsh #24 with modified v version

**Comment by Ccode-lang** [comment]
tested with second workaround

**Comment by jacobsalmela** [comment]
Looks like this PR just reverts back to a earlier version of vsh?  I can't really understand what your fix is here

**Comment by Ccode-lang** [comment]
It adds back the builtin code section

**Comment by Ccode-lang** [comment]
We could just add that in normally thou to. I just did not know where the builtins code was supposed to be.

**Comment by jacobsalmela** [comment]
They added a `coreutils`, which I was going to use instead.  Way better than anything I can make right now.

**Review by jacobsalmela — CHANGES_REQUESTED** [review]
If you can find some way to implement `coreutils` that would be helpful

**Comment by Ccode-lang** [comment]
ok.

**Comment by Ccode-lang** [comment]
coreutils is remakes of the gnu coreutils so it seems like we still need builtins

**Comment by Ccode-lang** [comment]
i'll delete and try to implement

**Comment by jacobsalmela** [comment]
I added #36

**Comment by Ccode-lang** [comment]
Ok 👍

**Pull request closed without merging**
